### ISSUE TITLE
デバッグしやすいように-pと-uがなくても動作するようにする

### ISSUE THREAD

**Issue by exKAZUu** [AI-comp/JavaChallenge2015#10]
`-p`がなければ`pause`しない，同様に，`-u`がなければ`unpause`しない．

**Comment by junk0612** [comment]
これを実装する場合、CLIを利用していると
`-a "java MyAI" -p "echo pause" -u "echo unpause" -a "java MyAI2"`
と
`-a "java MyAI" -a "java MyAI2" -p "echo pause" -u "echo unpause"`
の区別がつかなくなると思います(オプションがどういう順番で並んでいたかという情報は破棄されるため)。

**Comment by exKAZUu** [comment]
`-p`, `-u` は個数が0か4かのどちらかのみacceptしたい．
なので，指摘のような問題は起こらないはず．

**Comment by junk0612** [comment]
#12 で対応。
