### ISSUE TITLE
ログデータをJSON形式で標準出力に書き込む

### ISSUE THREAD

**Issue by exKAZUu** [AI-comp/JavaChallenge2015#17]
対戦システムに組み込む上で必須。仕様は以下のとおり。
# Game Engine

A game engine should return the following json object as a string via the standard output.

```
var gameResult = {
    log: [
      { target: 0, message: "log message for 1st AI" },
      { target: -1, message: "log message for all" },
      ...
    ],
    winner: 2,
    replay: [1, 2, 3],
};
```
- `log` is an array containing game logs for debug. Each log has an object with `target` and `message` fields.
  - `target` is an index of AI program whose owner can see the log. if `target` is -1 the log is shown to all users.
  - `message` is a content of log.
- `winner` is an index of the winning AI program. if `winner` is `''` (an empty string) it indicates there is no winner.
- `replay` is an object representing the replay data. You can design the object freely.
## JSON Examples

```
{ log: [{ target: 0, message: "log message for 1st AI" }, { target: -1, message: "log message for all" }], winner: 2, replay: [1, 2, 3] }
```

```
{ log: [], winner: "", replay: { seed: 111, commands: [2, 3, 1] } }
```

**Comment by exKAZUu** [comment]
JSONの処理は https://github.com/FasterXML/jackson が良いらしい

**Comment by junk0612** [comment]
現在、プレイヤーに送っている情報とReplayerのために出力しているログにはフォーマットの違いがあるのですが、プレイヤーに送っている情報のみをJSON形式にすればよいでしょうか？

**Comment by exKAZUu** [comment]
ゲームエンジン（このプログラム） => Webサーバ => Replayer というデータの流れ。
Webサーバは上述のreplayフィールドをReplayerに投げる。
ゲームエンジンは標準出力(`System.out`)に対して、上述の形式でリプレイデータや勝者などを出力しないと、Webサーバに組み込めない。
