### ISSUE TITLE
自分のプレイヤー番号を知るには？

### ISSUE THREAD

**Issue by gumfum** [AI-comp/JavaChallenge2015#18]
初期配置がランダムなので自分がどれを動かしてるか分からない気がしました
（ログと過去の自分のコマンドから頑張って調べれば良い話かもですが）

**Comment by exKAZUu** [comment]
確かに、これは修正が必要に感じる

**Comment by junk0612** [comment]
実装を見ていると、ログには出てないですがプレイヤーにはIDを与えているみたいです
Player#getAction()に書いてあります
(コードの引用ってどう書けばいいんだ...)

**Comment by gumfum** [comment]
プルリクじゃないと無理っぽい？
https://github.com/AI-comp/JavaChallenge2015/blob/master/src/main/java/net/aicomp/javachallenge2015/Player.java#L73-L77

確かにIDが出力されてたので、sample-log.md が間違ってる感じですかね

**Comment by junk0612** [comment]
いえ、おそらくログとプレイヤーに与える情報で書式が違うんだと思います
(サンプルログはそれを見てReplayerが動いているので大丈夫なはず)

**Comment by gumfum** [comment]
あ、なるほど
サンプルAIもちょっと修正します

**Comment by gumfum** [comment]
#22 でサンプルAIまで解決されました。
