### ISSUE TITLE
サンプルログの修正

### ISSUE THREAD

**Issue by junk0612** [AI-comp/JavaChallenge2015#32]
サンプルログでの1ターンの定義は**各プレイヤーが1回ずつ動く時間**として作成されているが、実装での1ターンの定義は**1人のプレイヤーが1回動く時間**となっているので統一する必要あり

**Comment by gumfum** [comment]
sample-log.md の修正でおｋですか？

**Comment by junk0612** [comment]
そうですね、その方向でお願いします
