### ISSUE TITLE
GameEngineTesterを開発する

### ISSUE THREAD

**Issue by exKAZUu** [AI-comp/JavaChallenge2015#5]

**Comment by exKAZUu** [comment]
https://github.com/AI-comp/GameEngineTester

**Comment by exKAZUu** [comment]
ゲームエンジンが対戦システムに組み込む上で必要な要件を満たしているか確認する。
具体的には、このリポジトリが持つテスト専用のAIプログラムを引数で渡してゲームエンジンを実行して、適切なデータのやり取りができ、pauae/unpauseが適切なタイミングで執行されていることを確認する。

**Comment by kenkoooo** [comment]
1. "EOD" が来るまでデータを受け取り続けて、 "EOD" が来たら適当なコマンドを返すAIを作る。
2. pause/unpause のコマンドとして echo 'pause' とかを適当に指定して、実際に動くかやってみる。

みたいな感じですか？

**Comment by exKAZUu** [comment]
https://github.com/AI-comp/GameEngineTester
このリポジトリで開発しますー
