### ISSUE TITLE
実行時引数のフォーマットを修正する

### ISSUE THREAD

**Issue by exKAZUu** [AI-comp/JavaChallenge2015#6]
以下の様な形式でお願いします！
`-a AI1_PROGRAM -p PAUSE_COMMAND_FOR_AI1 -u UNPAUSE_COMMAND_FOR_AI1 -a AI2_PROGRAM -p PAUSE_COMMAND_FOR_AI2 -u UNPAUSE_COMMAND_FOR_AI2 ...`

**Comment by exKAZUu** [comment]
できれば commons-cli (http://commons.apache.org/proper/commons-cli/) を使って欲しい．
以下でサンプルコードも示す．
https://github.com/AI-comp/GameEngineTester/blob/master/src/main/java/net/aicomp/game_engine_tester/Main.java

**Comment by exKAZUu** [comment]
依存関係は追加済み．

**Comment by junk0612** [comment]
実行時引数は4人分ではない場合もありますか？

**Comment by exKAZUu** [comment]
何人でも良いが、対戦システムは事前に決められた固定値にしか対応できない

**Comment by junk0612** [comment]
#7 で対応。
